"""Every message schema for Flick, as pydantic v2 models.

This module is the contract the entire system depends on. It is
frozen before any other work starts (ARCHITECTURE.md section 6) and
mirrored by hand in frontend/src/lib/types.ts. Every message carries
``type`` and ``ts`` (float, UNIX seconds).

Do not edit this file without following AGENTS.md section 4.
"""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, Field

# --------------------------------------------------------------------------
# 6.1 The selection contract
# --------------------------------------------------------------------------


class Selection(BaseModel):
    """The single most important type in the system.

    Everything upstream of it is replaceable.
    """

    type: Literal["input.selection"]
    ts: float
    trial_id: str  # must match the current trial or it is dropped
    target_idx: int  # 0..n_targets-1
    confidence: float  # 0..1, adapter-defined
    source: str  # "ssvep" | "keyboard" | "replay" | "emotiv"
    algorithm: str | None  # "fbcca" | "etrca" | None


# --------------------------------------------------------------------------
# 6.2 ZMQ: P1 sensor -> P3 backend (bci. prefix)
# --------------------------------------------------------------------------


class EegChunk(BaseModel):  # ~4 Hz
    type: Literal["bci.eeg"]
    ts: float
    fs: int
    channels: list[str]
    data: list[list[float]]  # [8][n], microvolts, post-filter
    railed: list[bool]


class PsdFrame(BaseModel):  # ~4 Hz
    type: Literal["bci.psd"]
    ts: float
    freqs: list[float]  # 0..48 Hz, 0.5 Hz bins
    power: list[float]  # occipital mean, dB
    peaks: list[float]  # power at each target frequency


class TargetScores(BaseModel):  # 4 Hz
    type: Literal["bci.scores"]
    ts: float
    algorithm: Literal["fbcca", "etrca"]
    rho: list[float]
    winner_idx: int
    margin: float
    above_threshold: bool
    dwell_count: int


class SensorSelection(BaseModel):  # topic "bci.selection", event
    """Emitted by the sensor process when its decision state machine fires.

    The ssvep input adapter (section 7.3) maps this onto the generic
    Selection of section 6.1. This is the raw, classifier-level
    event; Selection is the adapter-independent one the orchestrator
    consumes.
    """

    type: Literal["bci.selection"]
    ts: float
    trial_id: str
    target_idx: int
    rho: float
    margin: float
    algorithm: Literal["fbcca", "etrca"]


class SensorStatus(BaseModel):  # 1 Hz
    type: Literal["bci.status"]
    ts: float
    source: Literal["cyton", "synthetic", "replay"]
    connected: bool
    configured: bool  # has a stim.profile been received?
    samples_received: int
    dropped_samples: int
    railed_channels: list[int]


# --------------------------------------------------------------------------
# 6.3 WebSocket: dashboard -> P3 (client. prefix)
#
# The only inbound channel. Everything else the dashboard sends goes
# over REST (section 6.8); this exists for input that must be
# low-latency and ordered with the outbound stream. Inbound messages
# that fail validation are logged and dropped, never raised to the
# caller -- the dashboard is never trusted to drive anything
# destructive.
# --------------------------------------------------------------------------


class KeyPress(BaseModel):
    """Drives the keyboard input adapter (section 7.2).

    The backend forwards this to the active InputSource; adapters
    that do not consume key presses ignore it. Keys outside the
    configured target count are dropped.
    """

    type: Literal["client.key_press"]
    ts: float
    key: str  # "1".."5"


class RequestSnapshot(BaseModel):
    """Sent on every (re)connect.

    P3 replies with graph.snapshot and one sys.status so a
    reconnecting dashboard is immediately consistent.
    """

    type: Literal["client.request_snapshot"]
    ts: float


ClientMessage = Annotated[
    KeyPress | RequestSnapshot,
    Field(discriminator="type"),
]


# --------------------------------------------------------------------------
# 6.4 ZMQ: P3 -> P2 stimulus (stim. prefix)
# --------------------------------------------------------------------------


class ShowTargets(BaseModel):
    type: Literal["stim.show_targets"]
    ts: float
    trial_id: str
    labels: list[str]
    round: Literal["intent", "candidate", "speller"]
    cue_idx: int | None  # calibration only


class StimControl(BaseModel):
    type: Literal["stim.control"]
    ts: float
    action: Literal["idle", "start_flicker", "stop_flicker", "message"]
    message: str | None


# --------------------------------------------------------------------------
# 6.5 ZMQ: P2 -> P3 (stim. prefix)
# --------------------------------------------------------------------------


class StimulusProfile(BaseModel):
    """Published once at startup after measuring the real refresh rate.

    P3 relays it to P1, which reconfigures before its first classification.
    """

    type: Literal["stim.profile"]
    ts: float
    profile: Literal["hi", "lo"]
    measured_refresh_hz: float
    frequencies: list[float]
    phases: list[float]
    cancel_idx: int
    window_s: float
    bandpass_low_hz: float
    fbcca_subband_low_hz: list[float]


class StimulusOnset(BaseModel):
    type: Literal["stim.onset"]
    ts: float  # LSL-corrected
    trial_id: str
    frequencies: list[float]


class StimulusIntegrity(BaseModel):
    type: Literal["stim.integrity"]
    ts: float
    measured_refresh_hz: float
    dropped_frames_last_s: int
    frame_interval_std_ms: float


# --------------------------------------------------------------------------
# 6.6 WebSocket: P3 -> dashboard -- analytics.summary payload
# --------------------------------------------------------------------------


class AnalyticsSummary(BaseModel):
    """Payload of the analytics.summary WS message, every 2 s (section 6.6).

    accuracy_pct and itr_bits_per_min are nullable: both are undefined
    until a cued block (section 18.4) has run, because accuracy has no
    meaning without knowing what the user was supposed to pick.
    cued_trials counts how many cued trials have been recorded so far
    this session; when it is 0, SessionAnalytics.tsx greys those two
    tiles with "run a cued block to measure" instead of rendering a
    permanently blank chart, which reads as a bug during judging
    (section 18.3). Everything else here comes from free conversation
    and needs no cued block.
    """

    accuracy_pct: float | None
    itr_bits_per_min: float | None
    cued_trials: int
    mean_rho_by_target: list[float]
    selections_total: int
    mean_selection_latency_s: float
    drift: float


# --------------------------------------------------------------------------
# 6.7 Graph payload types (WebSocket: P3 -> dashboard)
# --------------------------------------------------------------------------


class GraphNode(BaseModel):
    """A node as rendered on the dashboard's 3D memory graph.

    label derivation (section 6.7): every node table except Memory has
    a `name` column; Memory has `text` instead. GraphService.snapshot()
    must derive label as:

        label = props.get("name") or props["text"][:60]

    Memory text is truncated to 60 characters because it is rendered
    on a 3D node, not read. Without this rule a Memory node raises
    KeyError: 'name' the first time the graph reaches the frontend.
    """

    id: str
    label: str
    kind: Literal["Person", "Place", "Thing", "Activity", "Need", "Memory"]
    weight: float
    last_accessed: float


class GraphEdge(BaseModel):
    id: str
    source: str
    target: str
    kind: str
    weight: float


# --------------------------------------------------------------------------
# Discriminated union over every message that carries a "type" field.
# --------------------------------------------------------------------------

BusMessage = Annotated[
    Selection
    | EegChunk
    | PsdFrame
    | TargetScores
    | SensorSelection
    | SensorStatus
    | ShowTargets
    | StimControl
    | StimulusProfile
    | StimulusOnset
    | StimulusIntegrity,
    Field(discriminator="type"),
]
